name: my_tasks
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  #HTTP
  dio: ^5.2.1+1
  retrofit: ^4.0.1
  #STATES
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  #DEVICE
  device_info_plus: ^9.0.2
  package_info_plus: ^4.0.2
  #ROUTER
  go_router: ^9.0.3
  #SCREEN
  responsive_framework: ^1.1.0
  #DESIGN
  fl_chart: ^0.63.0
  flutter_staggered_grid_view: ^0.6.2
  #DATABASE
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  #UTILS
  path_provider: ^2.0.15
  timeago: ^3.5.0
  intl: ^0.18.1

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  #GENERATOR
  build_runner: ^2.4.6
  freezed: ^2.4.1
  isar_generator: ^3.1.0+1
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1
  retrofit_generator: ^7.0.8

  flutter_lints: ^2.0.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/
