// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACLIhDqpTSN4PZQxOZ-OWg5Y1aT1uf9ns',
    appId: '1:32391270540:web:675befccec008db6d6eba9',
    messagingSenderId: '32391270540',
    projectId: 'counter-963d1',
    authDomain: 'counter-963d1.firebaseapp.com',
    storageBucket: 'counter-963d1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDomyjhkpHSbIVe34HejWcFsXAv6WFCJ6s',
    appId: '1:32391270540:android:91ec80075a43520bd6eba9',
    messagingSenderId: '32391270540',
    projectId: 'counter-963d1',
    storageBucket: 'counter-963d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEx6N4lvrr9wZuVp_FcpaYvOwBDeZVI0E',
    appId: '1:32391270540:ios:fecc1a09e70ce2fdd6eba9',
    messagingSenderId: '32391270540',
    projectId: 'counter-963d1',
    storageBucket: 'counter-963d1.appspot.com',
    iosBundleId: 'com.example.myTasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEx6N4lvrr9wZuVp_FcpaYvOwBDeZVI0E',
    appId: '1:32391270540:ios:fecc1a09e70ce2fdd6eba9',
    messagingSenderId: '32391270540',
    projectId: 'counter-963d1',
    storageBucket: 'counter-963d1.appspot.com',
    iosBundleId: 'com.example.myTasks',
  );
}
